version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
    volumes:
      - ./data:/app/data # Mount only necessary files

  worker:
    build: .
    container_name: worker
    restart: always
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_HOST=redis
    command:
      [
        "python",
        "-m",
        "celery",
        "-A",
        "src.celery.celery_app",
        "worker",
        "--loglevel=info",
        "--pool=threads",
        "-c",
        "4",
      ]

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80" # Serving from Nginx, no need for 3000
